# .github/workflows/lint-json.yml
name: Lint JSON (task1-jsonfix)

on:
  push:
    paths:
      - 'tasks/task1-jsonfix/data/**/*.json'
  pull_request:
    paths:
      - 'tasks/task1-jsonfix/data/**/*.json'

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Super-Linter (JSON only, scoped to folder)
        uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.MAVERICS }}
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: "true"
          VALIDATE_ALL_CODEBASE: "true"                  # scan the whole repo *but*…
          VALIDATE_JSON: "true"                          # …only run the JSON linter
          FILTER_REGEX_INCLUDE: "^tasks/task1-jsonfix/data/.*\\.json$"  # …and only in this dir
