---
config:
  look: neo
  layout: elk
  theme: mc
---
flowchart LR
    A["JSON Array [ ]"] --> I0["[0]"] & I1["[1]"] & I2["[2]"]
    I0 --> O0["Object { }"]
    I1 --> O1["Object { }"]
    I2 --> O2["Object { }"]